config/routes.rb
Ticketee2::Application.routes.draw do

  namespace :admin do
    root :to => "base#index"
    resources :users
  end

  devise_for :users

    root :to => "projects#index"
    resources :projects do
      resources :tickets
    end

end

app/models/ability.rb
def kjshfkajhfjdks
  puts "jksadfjkfsaf"
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name

  validates :name, :presence => true

  has_many :tickets, :dependent => :delete_all

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  attr_accessible :description, :title
  validates :title, :presence => true
  validates :description, :presence => true,
                          :length => { :minimum => 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  attr_accessible :email, :password, :admin, :as => :admin

def to_s
  "#{email} (#{admin? ? "Admin" : "User"})"
end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_filter :authorize_admin!

  def index
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

before_filter :find_user, :only => [:show, :edit, :update, :destroy]

  def index
    @users = User.all(:order => "email")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user], :as => :admin)
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render :action => "new"
    end
  end

  def edit
  end

  def show
  end

  def update
    @user.skip_reconfirmation!

    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update_attributes(params[:user], :as => :admin)
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash[:alert] = "User has not been updated."
      render :action => "edit"
    end

  end

  def destroy
    if @user == current_user
      flash[:alert] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User has been deleted."
    end
    redirect_to admin_users_path
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :find_project, :only => [:show,
                                       :edit,
                                       :update,
                                       :destroy]
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated. YAY!"
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated. Boo..."
      render :action => "edit"
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

private

  def find_project
    @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking" +
                    " for could not be found."
    redirect_to projects_path
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
before_filter :authenticate_user!, :except => [:index, :show]
before_filter :find_project
before_filter :find_ticket, :only => [:show, :edit, :update, :destroy]

def new
  @ticket = @project.tickets.build
end

def create
  @ticket = @project.tickets.build(params[:ticket])
  @ticket.user = current_user
  if @ticket.save
    flash[:notice] = "Ticket has been created."
    redirect_to [@project, @ticket]
  else
    flash[:alert] = "Ticket has not been created."
    render :action => "new"
  end
end

def show
end

def edit
end

def update
  if @ticket.update_attributes(params[:ticket])
    flash[:notice] = "Ticket has been updated."
    redirect_to [@project, @ticket]
  else
    flash[:alert] = "Ticket has not been updated."
    render :action => "edit"
  end
end

def destroy
  @ticket.destroy
  flash[:notice] = "Ticket has been deleted."
  redirect_to @project
end

private
  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_ticket
    @ticket = @project.tickets.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end

  def admins_only(&block)
    (block.call) if current_user.try(:admin?)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/base/index.html.erb
<%= link_to "Users", admin_users_path %>

Welcome to Ticketee's Admin Lounge. Please enjoy your stay.

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.check_box :admin %>
    <%= f.label :admin, "Is an admin?" %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<h2>Editing a User</h2>
<%= render "form" %>

app/views/admin/users/index.html.erb
<%= link_to "New User", new_admin_user_path %>
<ul id='users'>
  <% @users.each do |user| %>
    <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

app/views/admin/users/new.html.erb
<h2>New User</h2>
<%= render "form" %>

app/views/admin/users/show.html.erb
<h2><%= @user %></h2>
<%= link_to "Edit User", edit_admin_user_path(@user) %>
<%= link_to "Delete User", admin_user_path(@user), :method => :delete,
          :confirm => "Are you sure you want to delete this user?" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  <% if content_for?(:title) %>
    <%= yield(:title) %>
  <% else %>
    Ticketee
  <% end %>
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <div class='flash' id='<%= key %>'>
      <%= value %>
    </div>
  <% end %>
  <nav>
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %>
      <% admins_only do %>
        <%= link_to "Admin", admin_root_path %>
      <% end %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
  </nav>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<%= f.error_messages %>
<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</p>
  <%= f.submit %>
  <% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<% admins_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>

<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<h2><%= @project.name %></h2>
</br>
<p><b>Description: </b><%= @project.description %></p>
</br>

<% admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project", project_path(@project),
         :method => :delete,
         :confirm => "Are you sure you want to delete this project?" %>
<% end %>

<%= link_to "New Ticket", new_project_ticket_path(@project) %>

<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> -
      <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>

<%= link_to "Back To All Projects", projects_path %>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %> <co id="ch05_157_1"/>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br>
        </programlisting>
      </informalexample>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %>

app/views/tickets/show.html.erb
<div id='ticket'>
  <h2><%= @ticket.title %></h2>
  <span id='author'>Created by <%= @ticket.user.email %></span>
  <%= link_to "Edit Ticket", [:edit, @project, @ticket] %>
  <%= simple_format(@ticket.description) %>
  <%= link_to "Delete Ticket", [@project, @ticket], :method => :delete,
       :confirm => "Are you sure you want to delete this ticket?" %>
</div>
<%= link_to "Back To Project", project_path(@project) %>